services:
  portfolio:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: portfolio
    restart: unless-stopped
    env_file:
      - ./.env                # aquí defines MONGODB_URI
    networks:
      - proxy                 # conéctate a la red donde ya vive Mongo
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.portfolio.rule=Host(`jvillegas-portafolio.jvserver.com`)"
      - "traefik.http.routers.portfolio.entrypoints=websecure"
      - "traefik.http.routers.portfolio.tls=true"
      - "traefik.http.routers.portfolio.tls.certresolver=myresolver"
      - "traefik.http.routers.portfolio-http.rule=Host(`jvillegas-portafolio.jvserver.com`)"
      - "traefik.http.routers.portfolio-http.entrypoints=web"
      - "traefik.http.routers.portfolio-http.middlewares=redirect-to-https"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
      # Configuración para preservar cookies y cabeceras
      - "traefik.http.middlewares.portfolio-headers.headers.accesscontrolallowmethods=GET,OPTIONS,PUT,POST,DELETE"
      - "traefik.http.middlewares.portfolio-headers.headers.accesscontrolalloworigin=*"
      - "traefik.http.middlewares.portfolio-headers.headers.accesscontrolmaxage=100"
      - "traefik.http.middlewares.portfolio-headers.headers.addvaryheader=true"
      # Aplicar middleware de cabeceras a rutas
      - "traefik.http.routers.portfolio.middlewares=portfolio-headers"
    expose:
      - 3000

networks:
  proxy:
    external: true