version: '3.8'
services:
  # Servicio de Next.js (Portfolio)
  portfolio:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: portfolio_app
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - MONGODB_URI=mongodb://portfolio_db:27017/portfolio
      - NEXT_DISABLE_STATIC_GENERATION=true
    depends_on:
      - mongodb
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.portfolio.rule=Host(`jvillegas-portafolio.jvserver.com`)"
      - "traefik.http.routers.portfolio.entrypoints=websecure"
      - "traefik.http.routers.portfolio.tls=true"
      - "traefik.http.routers.portfolio.tls.certresolver=myresolver"
      - "traefik.http.routers.portfolio-http.rule=Host(`jvillegas-portafolio.jvserver.com`)"
      - "traefik.http.routers.portfolio-http.entrypoints=web"
      - "traefik.http.routers.portfolio-http.middlewares=redirect-to-https"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"

  # Servicio de MongoDB
  mongodb:
    image: mongo:6
    container_name: portfolio_db
    restart: unless-stopped
    volumes:
      - mongodb_data:/data/db
    networks:
      - proxy

volumes:
  mongodb_data:
    driver: local

networks:
  proxy:
    external: true